[package]
name = "rust_for_multimedia_canny"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
rayon = "1.5.1"
itertools = "0.10.3"